title: Radic builder
description: Custom JS Library builder using jQuery's build method

url: //robinradic.github.io


layouts: ./_includes/_layouts
data_source: ./_includes/_data



# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Amsterdam/Netherlands
future:      true

sass:
  sass_dir: _sass
  style: compressed